[package]
name = "imo"
version = "0.1.0"
edition = "2024"

[dependencies]
gimli = "0.33.0"
memmap2 = "0.9.10"
nix = { version = "0.31.3", features = ["process", "ptrace", "signal", "personality", "uio"] }
object = "0.39.1"
owo-colors = "4.3.0"
rustc-hash = "2.1.2"
thiserror = "2.0.20"

[dependencies.iced-x86]
version = "1.21.0"
default-features = false
features = ["decoder", "std"]
