[target.x86_64-apple-darwin]
runner = ["sh", "-c", "codesign --entitlements entitlements.plist --force -s - \"$0\" && \"$0\" \"$@\""]

[target.aarch64-apple-darwin]
runner = ["sh", "-c", "codesign --entitlements entitlements.plist --force -s - \"$0\" && \"$0\" \"$@\""]

