pub mod breakpoint;
pub mod error;
pub mod execution;
pub mod types;
pub mod variable;

use gimli::UnwindSection;
use rustc_hash::FxHashMap;
use std::path::Path;

use crate::dwarf::debug_info::{DebugVariable, ParamType};
use crate::session::types::StackInfo;
use crate::sys::{ProcessAddressRanges, SystemError};
use crate::sys::os::{self, syscalls};
use crate::sys::registers::RegisterViewer;
use crate::types::{
    FileIndices, LineRow, SourceCodeCache, SourceCodeDisplay, SourceLocation, StringId,
    StringInterner, UniqueFileId,
};
use crate::{
    dwarf::{
        self,
        debug_frame::{RawDebugFrame, setup_session_debug_frame},
        debug_info::{ActiveParamsContext, DebuggerMetadataCache},
        error::CacheSetupError,
    },
    sys::registers::VirtualRegisters,
};
use breakpoint::{BreakpointData, BreakpointMutationResult, BreakpointTarget, ManagedBreakpoint};
use execution::CurrentStopCmd;
use variable::DebugValue;




/// Cache for entire debug session
#[derive(Debug)]
pub struct DebugSession {
    // Breakpoint data
    pub line_index: FxHashMap<u32, Vec<BreakpointTarget>>,
    pub address_ranges: ProcessAddressRanges,
    pub breakpoint_index_tracker: Vec<Option<BreakpointData>>,

    pub line_row: Vec<LineRow>,

    pub base_address: u64,
    // A global arena to consolidate repetitive string allocations into one location
    pub interner: StringInterner,

    // Map the index of a file directly to the offset generated by gimli
    pub file_indices: FileIndices,

    pub source_file: SourceCodeCache,

    // Metdata
    pub metadata: DebuggerMetadataCache,

    // Tracking the current state the debugger is in
    pub current_cmd: CurrentStopCmd,

    // Debug frame for finding CFA
    pub raw_debug_frame: RawDebugFrame,

    // Current register states
    pub registers: Option<RegisterViewer>,

    // Different for each os
    pub active_breakpoints: FxHashMap<u64, ManagedBreakpoint>,
    pub pid: os::ProcessId,
}

impl DebugSession {
    /// Instantiate the struct with default values
    fn from_pid(pid: os::ProcessId) -> Self {
        Self {
            address_ranges: ProcessAddressRanges::default(),
            base_address: 0,
            breakpoint_index_tracker: Vec::new(),
            line_index: FxHashMap::default(),
            metadata: DebuggerMetadataCache::default(),
            raw_debug_frame: RawDebugFrame::default(),
            current_cmd: CurrentStopCmd::default(),
            active_breakpoints: FxHashMap::default(),
            interner: StringInterner::default(),
            source_file: SourceCodeCache::default(),
            line_row: Vec::new(),
            file_indices: FileIndices::default(),
            registers: None,
            pid,
        }
    }

    // =================================================================
    // OS Specific functions
    // =================================================================

    /// Create a complete instance of the session cache
    pub fn new(
        pid: os::ProcessId,
        binary_path: &str,
    ) -> Result<Self, dwarf::error::CacheSetupError> {
        let mut session = Self::from_pid(pid);

        let file = std::fs::File::open(binary_path)?;

        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        let object = object::File::parse(&*mmap)?;

        session.update_process_addresses()?;

        session.metadata = DebuggerMetadataCache::new(&object)?;

        // Update line index and address to location
        dwarf::debug_line::setup_session_cache(&object, &mut session)?;

        session.raw_debug_frame = setup_session_debug_frame(&object)?;

        session.set_up_line_row();

        Ok(session)
    }

    /// Remove unnecessary ranges and sort the address for binary search lookup
    pub fn set_up_line_row(&mut self) {
        self.line_row
            .retain(|range| range.start_address >= self.metadata.text_address);

        self.line_row.sort_by_key(|l| l.start_address);
    }

    pub fn find_line_range(&self, current_pc: u64) -> Option<&LineRow> {
        match self.line_row.binary_search_by(|p| {
            if current_pc < p.start_address {
                std::cmp::Ordering::Greater
            } else if current_pc >= p.end_address {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        }) {
            Ok(index) => Some(&self.line_row[index]),
            Err(_) => None,
        }
    }

    /// Get the live register of the current process
    pub fn get_regs(&self) -> Result<RegisterViewer, SystemError> {
        if let Some(regs) = self.registers {
            return Ok(regs);
        }

        // Backup in case the register was not instantiated for some reason
        let regs = syscalls::get_regs(self.pid)?;
        Ok(RegisterViewer { regs })
    }

    pub fn invalidate_register(&mut self) {
        self.registers = None;
    }

    /// Create a specific breakpoint at a given address
    pub fn create_specific_breakpoint(&mut self, relative_address: u64) -> Result<(), SystemError> {
        let absolute_address = self.get_absolute_address(relative_address);

        // If breakpoint already exists dont write simply increment the reference counter
        if let Some(managed_breakpoint) = self.active_breakpoints.get_mut(&absolute_address) {
            managed_breakpoint.ref_count += 1;
            return Ok(());
        }

        #[allow(unused_mut)]
        // First time seeing the address
        // Create the breakpoint
        let mut breakpoint = os::PlatformBreakpoint::new(absolute_address);
        breakpoint.enable(self.pid)?;

        self.active_breakpoints
            .insert(absolute_address, ManagedBreakpoint::new(breakpoint));

        Ok(())
    }

    pub fn get_unwind_table(&self) -> gimli::EhFrame<gimli::EndianSlice<'_, gimli::RunTimeEndian>> {
        self.raw_debug_frame
            .get_unwind_table_with_endian(self.metadata.endian)
    }

    pub fn get_register_value(
        &self,
        register: gimli::Register,
        virtual_registers: &VirtualRegisters,
    ) -> Option<u64> {
        #[cfg(target_os = "linux")]
        {
            match register.0 {
                6 => Some(virtual_registers.base_pointer),
                7 => Some(virtual_registers.stack_pointer),
                16 => Some(virtual_registers.instruction_pointer),
                _ => todo!("Not implemented yet {}", register.0),
            }
        }

        #[cfg(not(target_os = "linux"))]
        {
            std::hint::black_box((virtual_registers, register));
            Some(0)
        }
    }

    pub fn backtrace(&self) -> Result<Vec<StackInfo<'_>>, SystemError> {
        let mut stack_frames = Vec::new();
        let mut virtual_registers = self.virtual_registers()?;

        loop {
            if !self.address_ranges.within_range(virtual_registers.instruction_pointer) {
                 break;
            }

            let current_pc = virtual_registers.instruction_pointer - self.base_address;

            let trace = self.metadata.get_function_trace(current_pc);

            if trace.is_empty() {
                let _ = self.get_return_address(&mut virtual_registers);
                continue;
            }

            for scope in trace {
                match &scope.scope {
                    dwarf::debug_info::ExecutionScope::Function {
                        display_name,
                        decl_file_id,
                        decl_line,
                        ..
                    } => {
                        if let Some(file) = self.file_idx_to_str(decl_file_id) {
                            stack_frames.push(StackInfo::Function {
                                func_name: display_name,
                                file,
                                rip: virtual_registers.instruction_pointer,
                                line: *decl_line,
                            });
                        }
                    }
                    dwarf::debug_info::ExecutionScope::Inlined {
                        name: inlined_name,
                        unit_offset,
                        call_file_idx,
                        decl_file_idx,
                        decl_line,
                        call_line,
                    } => {
                        let call_file_id = UniqueFileId {
                            offset: *unit_offset,
                            file_idx: *call_file_idx,
                        };
                        if let Some(call_file) = self.file_idx_to_str(&call_file_id) {
                            let decl_file_id = UniqueFileId {
                                offset: *unit_offset,
                                file_idx: *decl_file_idx,
                            };
                            if let Some(decl_file) = self.file_idx_to_str(&decl_file_id) {
                                stack_frames.push(StackInfo::Inlined {
                                    func_name: inlined_name,
                                    decl_file,
                                    call_file,
                                    rip: virtual_registers.instruction_pointer,
                                    call_line: *call_line,
                                    decl_line: *decl_line,
                                });
                            }
                        }
                    }
                    _ => unreachable!(),
                }
            }

            let _ = self.get_return_address(&mut virtual_registers);
        }

        Ok(stack_frames)
    }

    pub fn file_idx_to_str(&self, file_idx: &crate::types::UniqueFileId) -> Option<&str> {
        let id = self.file_indices.get(file_idx)?;
        self.interner.get_str(*id)
    }

    pub fn get_return_address(&self, regs: &mut VirtualRegisters) -> Option<u64> {
        let eh_frame = self.get_unwind_table();
        let base_addresses = &self.metadata.base_addresses;

        let current_pc = regs.instruction_pointer - self.base_address;

        if let Ok(fde) =
            eh_frame.fde_for_address(base_addresses, current_pc, |sections, bases, offset| {
                sections.cie_from_offset(bases, offset)
            })
        {
            let mut ctx = gimli::UnwindContext::new();
            let mut table = fde.rows(&eh_frame, base_addresses, &mut ctx).ok()?;

            let ra_register = fde.cie().return_address_register();
            while let Some(row) = table.next_row().ok()? {
                let cfa_address = match row.cfa() {
                    gimli::CfaRule::RegisterAndOffset { register, offset } => {
                        let reg_value = self.get_register_value(*register, &regs)?;
                        (reg_value as i64 + offset) as u64
                    }
                    gimli::CfaRule::Expression(_) => todo!(),
                };

                if row.contains(current_pc) {
                    regs.stack_pointer = cfa_address;

                    // TODO: get base pointer dynamically
                    // regs.base_pointer = cfa_address - 16;

                    if let Some(ra_rule) = row.register(ra_register) {
                        let return_address = match ra_rule {
                            gimli::RegisterRule::Offset(offset) => {
                                let ra_storage_address = (cfa_address as i64 + offset) as u64;

                                let return_address =
                                    syscalls::peek_data(self.pid, ra_storage_address).ok()? as u64;
                                Some(return_address)
                            }
                            gimli::RegisterRule::Register(saved_reg) => {
                                let return_address = self.get_register_value(saved_reg, &regs)?;
                                Some(return_address)
                            }
                            _ => todo!(),
                        };

                        if let Some(addr) = return_address {
                            regs.instruction_pointer = addr;
                        }

                        return return_address;
                    }
                }
            }
        }
        None
    }

    pub fn virtual_registers(&self) -> Result<VirtualRegisters, SystemError> {
        let full_regs = self.get_regs()?;
        Ok(full_regs.into())
    }

    pub fn current_instruction_pointer(&self) -> Result<u64, SystemError> {
        self.get_regs().map(|r| r.instruction_pointer())
    }

    pub fn current_stack_pointer(&self) -> Result<u64, SystemError> {
        self.get_regs().map(|r| r.stack_pointer())
    }

    pub fn current_pc(&self) -> Result<u64, SystemError> {
        let pc = self.current_instruction_pointer()? - self.base_address;
        Ok(pc)
    }

    /// Continue session from last interrupt
    pub fn continue_session(&self) -> Result<(), SystemError> {
        syscalls::continue_session(self.pid)
    }

    pub fn send_trap_signal(&self) -> Result<(), SystemError> {
        syscalls::send_trap_signal(self.pid)
    }

    // ========================================
    // CLI Commands
    // ========================================

    pub fn is_idle(&self) -> bool {
        self.current_cmd.is_idle()
    }

    pub fn toggle_running(&mut self) {
        self.current_cmd = CurrentStopCmd::Running;
    }
    pub fn toggle_continue(&mut self) {
        self.current_cmd = CurrentStopCmd::Continuing;
    }

    pub fn complete_single_step(&mut self) -> Result<(), SystemError> {
        self.invalidate_register();
        self.current_cmd = CurrentStopCmd::SingleStep;
        self.single_step()
    }

    pub fn begin_step_into(&mut self) -> Result<(), SystemError> {
        self.invalidate_register();
        let Some(current_location) = self.current_location() else {
            self.current_cmd = CurrentStopCmd::SearchingForValidLocation;
            self.single_step()?;
            return Ok(());
        };

        self.current_cmd = CurrentStopCmd::StepInto {
            start_file: current_location.file,
            start_line: current_location.line,
        };
        self.single_step()
    }

    pub fn begin_step_over(&mut self) -> Result<(), SystemError> {
        self.invalidate_register();
        let Some(current_location) = self.current_location() else {
            self.current_cmd = CurrentStopCmd::SearchingForValidLocation;
            self.single_step()?;
            return Ok(());
        };

        let is_inline = self.metadata.is_in_inline(self.current_pc()?);

        self.current_cmd = CurrentStopCmd::StepOver {
            start_stack_pointer: self.current_stack_pointer()?,
            start_file: current_location.file,
            start_line: current_location.line,
            started_from_inline: is_inline,
        };
        self.single_step()
    }

    pub fn begin_finish(&mut self) -> Result<(), SystemError> {
        self.invalidate_register();
        let is_inline = self.metadata.is_in_inline(self.current_pc()?);

        self.current_cmd = CurrentStopCmd::Finish {
            start_stack_pointer: self.current_stack_pointer()?,
            started_from_inline: is_inline,
        };
        self.single_step()
    }

    pub fn current_location(&self) -> Option<&SourceLocation> {
        let abs = self.current_instruction_pointer().ok()?;
        let rel_addr = self.get_relative_address(abs);
        self.get_location_with_address(rel_addr)
    }

    pub fn get_or_create_source_file(&mut self, path: &Path, line: u32) -> Option<&str> {
        if let Some(entry) = self.source_file.get_line_entry(path, line) {
            // Returning normally confuses compiler
            // NOTE: This is safe because entry is guaranteed to exist simply casting it as a raw pointer
            unsafe { return Some(&*(entry as *const str)) }
        }
        self.source_file.create_and_get_line_entry(path, line)
    }

    pub fn get_source_file(&mut self, path: &Path, line_number: u32) -> SourceCodeDisplay {
        if let Some(source_code) = self.get_or_create_source_file(path, line_number) {
            return SourceCodeDisplay::FullyResolved {
                source_code: Box::from(source_code),
                line_number,
            };
        }

        SourceCodeDisplay::PartiallyResolved {
            path: Box::from(path),
            line_number,
        }
    }

    pub fn get_current_source_file(&mut self) -> SourceCodeDisplay {
        let Some(current_location) = self.current_location().copied() else {
            return SourceCodeDisplay::Unresolved;
        };

        let Some(path_string) = self.interner.get_string(current_location.file) else {
            return SourceCodeDisplay::CacheCorrupt {
                id: current_location.file,
            };
        };

        let path = Path::new(&path_string);
        let line_number = current_location.line;

        self.get_source_file(path, line_number)
    }

    pub fn get_current_list_entry(&mut self) -> Option<Vec<SourceCodeDisplay>> {
        let mut list = Vec::with_capacity(11);

        let start_location = self.current_location().copied()?;
        let path_str = self.interner.get_string(start_location.file)?;

        let path = Path::new(&path_str);

        let max_number = self.source_file.get_entry_line_count(path)? as u32;

        let start_line_number = start_location.line.saturating_sub(1);

        let low_range = start_line_number.saturating_sub(5);
        let high_range = max_number.min(start_line_number + 5);

        let mut current_line = low_range;

        while high_range >= current_line {
            let line_val = self.get_source_file(path, current_line);
            list.push(line_val);
            current_line += 1;
        }

        Some(list)
    }

    /// Move forward from the specified stop
    pub fn single_step(&self) -> Result<(), SystemError> {
        syscalls::step(self.pid)
    }

    /// Kill the current session
    pub fn kill_session(&self) -> Result<(), SystemError> {
        syscalls::kill_session(self.pid)
    }

    /// Get and update the process base address
    pub fn update_process_addresses(&mut self) -> Result<(), CacheSetupError> {
        syscalls::update_process_addresses(self, self.pid)
    }

    // =================================================================
    // Other Methods
    // =================================================================

    /// Obtain the location that an address belongs to within the program
    pub fn get_location_with_address(&self, relative_address: u64) -> Option<&SourceLocation> {
        self.find_line_range(relative_address).map(|l| &l.location)
    }

    /// Get the relative address from absolute address
    pub fn get_relative_address(&self, absolute_address: u64) -> u64 {
        absolute_address - self.base_address
    }

    /// Find current scope with internal pc
    pub fn find_specified_param(
        &self,
        param_type: ParamType,
    ) -> Result<ActiveParamsContext<'_>, SystemError> {
        let current_pc = self.current_instruction_pointer()? - self.base_address;
        let context = self.metadata.find_scope_by_pc(current_pc, param_type);
        Ok(context)
    }

    /// Get all variable names and value within the current scope
    pub fn get_all_values_for_specified_param(
        &self,
        param_type: ParamType,
    ) -> Result<Vec<(String, Option<DebugValue>)>, SystemError> {
        let current_scope = self.find_specified_param(param_type)?;
        let mut local_variables = Vec::with_capacity(current_scope.params.len());

        for var in current_scope.params {
            let value = self.var_to_value(var, current_scope.frame_base);
            local_variables.push((var.name.clone(), value));
        }

        Ok(local_variables)
    }

    /// Attempt to parse the variable to its value
    /// If any issue occurs down the road, dont throw an error, simply return None
    pub fn var_to_value(
        &self,
        var: &DebugVariable,
        frame_base: Option<&Vec<u8>>,
    ) -> Option<DebugValue> {
        let regs = self.get_regs().ok()?;

        let endian = self.metadata.endian;
        let abi = &self.metadata.abi;
        let encoding = self.metadata.encoding?;

        let frame_base = frame_base?;

        let address = var
            .parse_value(
                &regs,
                encoding,
                endian,
                abi,
                frame_base,
                &self.metadata.type_index,
                self.pid,
                &self.address_ranges
            )
            .ok()??;

        if let Some(ty) = self.metadata.type_index.get(&var.target_type_offset) {
            let result = ty
                .dwarf_type
                .to_debug_value(&self.metadata.type_index, address, self.pid, &self.address_ranges)
                .ok()?;

            return result;
        }

        None
    }

    /// Get the value of a variable with the given name
    /// Requires current scope to evaluate the value
    pub fn get_param_value(
        &self,
        node: &ActiveParamsContext,
        name: &str,
    ) -> Result<Option<DebugValue>, error::VariableParseError> {
        let regs = self.get_regs()?;

        let endian = self.metadata.endian;
        let abi = &self.metadata.abi;
        let Some(encoding) = self.metadata.encoding else {
            return Err(error::VariableParseError::Encoding);
        };

        // Since rust does not declare variables in sequential order
        // We store the actual order the variables were actually declared
        // We use this to check if the decl_line is before our current index
        // If it is that means it has been declared and if not then it hasnt

        if let Some(param) = node.get_param_with_name(name) {
            let Some(frame_base) = node.frame_base else {
                return Err(error::VariableParseError::FrameBase);
            };

            // Get the variable's address
            let Some(address) = param.parse_value(
                &regs,
                encoding,
                endian,
                abi,
                frame_base,
                &self.metadata.type_index,
                self.pid,
                &self.address_ranges
            )?
            else {
                return Err(error::VariableParseError::Address);
            };

            // Resolve the variable's live value with address and current pid
            if let Some(ty) = self.metadata.type_index.get(&param.target_type_offset) {
                let result =
                    ty.dwarf_type
                        .to_debug_value(&self.metadata.type_index, address, self.pid, &self.address_ranges)?;

                return Ok(result);
            }
        }
        Ok(None)
    }

    /// Clear all breakpoint for line_number by default
    /// Only clear specified breakpoints if file name is provided
    pub fn clear_breakpoint(
        &mut self,
        line_number: u32,
        file: Option<&str>,
    ) -> Result<Vec<usize>, SystemError> {
        let mut cleared_breakpoints = Vec::new();
        let mut bp_idx = Vec::new();

        let filter_by_file = file.is_some();

        // Map every breakpoints that macthes the user's choice into being None
        // Store these breakpoints and their indices
        for (idx, opt_bp) in self.breakpoint_index_tracker.iter_mut().enumerate() {
            if let Some(bp) = opt_bp {
                if !filter_by_file {
                    if bp.line == line_number {
                        if let Some(removed_bp) = opt_bp.take() {
                            cleared_breakpoints.push(removed_bp);
                            bp_idx.push(idx + 1);
                        }
                    }
                } else {
                    if let Some(bp_file) = bp.file.to_str() {
                        // Safe unwrap since this is the path where the file is Some
                        if bp.line == line_number && bp_file.ends_with(file.unwrap()) {
                            if let Some(removed_bp) = opt_bp.take() {
                                cleared_breakpoints.push(removed_bp);
                                bp_idx.push(idx + 1);
                            }
                        }
                    } else {
                        eprintln!("[Warning] Failed to convert file path at index {}", idx)
                    }
                }
            }
        }

        for data in cleared_breakpoints.iter() {
            for bp in data.target.iter() {
                self.clear_specific_breakpoint(bp.relative_address)?
            }
        }

        Ok(bp_idx)
    }

    /// Enable breakpoint at a specific index in the tracker
    pub fn enable_breakpoint(
        &mut self,
        index: usize,
    ) -> Result<BreakpointMutationResult, SystemError> {
        // NOTE: Safe index, bounds are checked by the cli
        let target = self.breakpoint_index_tracker[index].clone();

        if let Some(mut data) = target {
            // If already enabled, DO NOTHING
            if data.enabled {
                return Ok(BreakpointMutationResult::AlreadyInState);
            }

            for bp in data.target.iter() {
                self.create_specific_breakpoint(bp.relative_address)?
            }

            data.enabled = true;

            // Update the actual session instance
            self.breakpoint_index_tracker[index] = Some(data);
            return Ok(BreakpointMutationResult::Updated);
        }

        Ok(BreakpointMutationResult::NotFound)
    }

    /// Disable breakpoint and returns true if successful
    pub fn disable_breakpoint(
        &mut self,
        index: usize,
    ) -> Result<BreakpointMutationResult, SystemError> {
        // NOTE: Safe index, bounds are checked by the cli
        let target = self.breakpoint_index_tracker[index].clone();

        if let Some(mut data) = target {
            // If already disabled, DO NOTHING
            if !data.enabled {
                return Ok(BreakpointMutationResult::AlreadyInState);
            }

            for bp in data.target.iter() {
                self.clear_specific_breakpoint(bp.relative_address)?;
            }

            data.enabled = false;

            // Update the actual session instance
            self.breakpoint_index_tracker[index] = Some(data);
            return Ok(BreakpointMutationResult::Updated);
        }

        Ok(BreakpointMutationResult::NotFound)
    }

    /// Deletes breakpoint and returns true if successful
    pub fn delete_breakpoint(
        &mut self,
        index: usize,
    ) -> Result<BreakpointMutationResult, SystemError> {
        // NOTE: Safe index, bounds are checked by the cli
        let target = self.breakpoint_index_tracker[index].take();

        if let Some(data) = target {
            for bp in data.target.iter() {
                self.clear_specific_breakpoint(bp.relative_address)?
            }
            return Ok(BreakpointMutationResult::Updated);
        }

        Ok(BreakpointMutationResult::NotFound)
    }

    /// Create breakpoint(s) at a file on a given line number
    /// Returns the number of breakpoint targets that were found on the given line alongside the address/first target if multiple addresses exist
    pub fn create_breakpoint(
        &mut self,
        line_number: u32,
        file: &Path,
    ) -> Result<BreakpointMutationResult, SystemError> {
        let Some(line_index) = self.get_breakpoint_target(line_number) else {
            return Ok(BreakpointMutationResult::NotFound);
        };

        let line_index: Vec<BreakpointTarget> = line_index
            .into_iter()
            .filter(|bp| *bp.file == *file)
            .collect();

        let mut bp_for_line = 0;
        for bp in line_index.iter() {
            self.create_specific_breakpoint(bp.relative_address)?;
            bp_for_line += 1;
        }

        self.breakpoint_index_tracker
            .push(Some(BreakpointData::from_target(
                line_index.clone(),
                line_number,
                file,
            )));

        Ok(BreakpointMutationResult::Created {
            count: bp_for_line as u8,
            target: line_index[0].clone(),
        })
    }

    /// Get the current index of the breakpoint the user is currently on
    pub fn current_index(&self) -> usize {
        // Index is one based for the user
        self.breakpoint_index_tracker.len()
    }

    /// Clear breakpoint at specfic breakpoint address
    pub fn clear_specific_breakpoint(&mut self, relative_address: u64) -> Result<(), SystemError> {
        let absolute_address = self.get_absolute_address(relative_address);
        let mut should_remove = false;

        // If breakpoint doesnt exist, simply ignore it
        if let Some(managed_breakpoint) = self.active_breakpoints.get_mut(&absolute_address) {
            if managed_breakpoint.ref_count > 1 {
                // Other breakpoints exist, dont remove it, simply decrement
                managed_breakpoint.ref_count -= 1;
            } else {
                managed_breakpoint.breakpoint.disable(self.pid)?;
                should_remove = true;
            }
        }

        if should_remove {
            self.active_breakpoints.remove(&absolute_address);
        }

        Ok(())
    }

    /// Get absolute address ( the sum of base address and absolute address )
    pub fn get_absolute_address(&self, relative_address: u64) -> u64 {
        self.base_address + relative_address
    }

    /// Get breakpoint target (file name and relative address ) from line number and file name
    pub fn get_specific_breakpoint_target(
        &self,
        file_name: &str,
        line_number: u32,
    ) -> Vec<BreakpointTarget> {
        let Some(line_index) = self.get_breakpoint_target(line_number) else {
            return vec![];
        };

        line_index
            .into_iter()
            .filter(|x| x.file.ends_with(file_name))
            .collect()
    }

    /// Get breakpoint target (file name and relative_address ) from the just line number
    pub fn get_breakpoint_target(&self, line_number: u32) -> Option<Vec<BreakpointTarget>> {
        let line_index = self.line_index.get(&line_number);
        line_index.cloned()
    }
}
